dist: xenial
language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.7"
  - "nightly"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
env:
  global:
    - DEVPI_INDEX="devpi-travis/${TRAVIS_REPO_SLUG/\//_}_${TRAVIS_BRANCH/\//_}"
  matrix:
    - PROJECT=common
    - PROJECT=web
    - PROJECT=client
install: travis_retry pip install tox-travis devpi-client
script:
  - export DEVPI_INDEX_URL="https://pypi.org/simple/"
  - test "${DEVPI_TRAVIS_PASSWD}" != "" && export DEVPI_INDEX_URL="https://m.devpi.net/${DEVPI_INDEX}" || true
  - echo "${DEVPI_INDEX_URL}"
  - cd $PROJECT
  - travis_retry tox -i "${DEVPI_INDEX_URL}" --pre
stages:
  - name: create packages
    if: type IN (push, api, cron)
  - test
jobs:
  include:
    - stage: create packages
      addons: []
      install: travis_retry pip install devpi-client "towncrier<18.6.0"
      python: "2.7"
      env: []
      script:
        - devpi use https://m.devpi.net/devpi-travis
        - devpi login devpi-travis --password ${DEVPI_TRAVIS_PASSWD}
        - yes yes | devpi index --delete "${DEVPI_INDEX}" || true
        - devpi index -c "${DEVPI_INDEX}" bases=root/pypi
        - devpi use "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==4.0.0 "${DEVPI_INDEX}"
        - devpi push --index root/pypi devpi-server==4.2.1 "${DEVPI_INDEX}"
        - cd ${TRAVIS_BUILD_DIR}/common
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/server
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/web
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/client
        - yes | towncrier
        - devpi upload
        - cd ${TRAVIS_BUILD_DIR}/postgresql
        - yes | towncrier
        - devpi upload

    #########################
    #
    # server
    #
    #########################
    - stage: test
      python: "2.7"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    - stage: test
      python: "3.4"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    - stage: test
      python: "3.7"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    - stage: test
      python: "nightly"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    - stage: test
      python: "pypy2.7-6.0"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    - stage: test
      python: "pypy3.5-6.0"
      env: PROJECT=server
      addons:
        apt:
          packages:
            - nginx

    #########################
    #
    # postgresql
    #
    #########################

    - stage: test
      python: "3.4"
      env: PROJECT=postgresql
      addons:
        apt:
          packages:
            - nginx
        postgresql: "9.5"

    - stage: test
      python: "pypy3.5-6.0"
      env: PROJECT=postgresql
      addons:
        apt:
          packages:
            - nginx
        postgresql: "9.5"
