[mypy]
files = .
show_error_codes = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unused_ignores = True
warn_unreachable = True
python_version = 3.11

# step 1: add types to functions
# step 2: check_untyped_defs = True and disallow_incomplete_defs = True
# step 3: disallow_untyped_defs = True
